spring:
  profiles:
    - default
    - test
    - postgres
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: true
server:
  port: ${API_PORT}
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}